### PR TITLE
Added new content field to allow specify content in embeds.

### PR DESCRIPTION
**Pull request by hokiepokedad2**
Content field added to all trackings pages (add and edit) to specify what content to include in outgoing messages. Values are stored in the respective object tables' "ping" column.

### CODE REVIEW

**Comment by jfberry** [comment]
Ping field is added to content on outbound messages with the intention of pinging users

eg

!track everything iv100 @hundos

would add @hundos to the ping field to be used to wake up appropriate group. 

Does this pr align with this use?

**Comment by bbdoc** [comment]
I think adding this for users will be more confusing than anything else, and I don't really see much use case for it, so could you please add a condition to displaying the field ? 

Wrapping it inside an `if` should do it :

```
if (!str_contains($_SESSION['type'], ':user')) { 
    ----
    ----
}
```

I'll probably merge that after I have merged templates to make sure we have no conflict between those 2 as we are updating the same set of files.

**Comment by hokiepokedad2** [comment]
> I think adding this for users will be more confusing than anything else, and I don't really see much use case for it, so could you please add a condition to displaying the field ?
> 
> Wrapping it inside an `if` should do it :
> 
> ```
> if (!str_contains($_SESSION['type'], ':user')) { 
>     ----
>     ----
> }
> ```
> 
> I'll probably merge that after I have merged templates to make sure we have no conflict between those 2 as we are updating the same set of files.

Okay no problem. `str_contains` is a new function of PHP8. Is PHP8 a requirement for PoracleWeb?

**Comment by bbdoc** [comment]
> Okay no problem. `str_contains` is a new function of PHP8. Is PHP8 a requirement for PoracleWeb?

Good remark, maybe use `strpos` instead so we don't have to add php8 as a requirement.

**Comment by hokiepokedad2** [comment]
> Good remark, maybe use `strpos` instead so we don't have to add php8 as a requirement.

Changes made. Also included the value if it exists on each respective display card.

**Comment by bbdoc** [comment]
Looking good. Could you just add a screenshot of how it looks like on display screen in description ? As I don't use templates myself I cannot really check it.

**Comment by hokiepokedad2** [comment]
> Looking good. Could you just add a screenshot of how it looks like on display screen in description ? As I don't use templates myself I cannot really check it.

Pokemon Display (Desktop)
https://i.imgur.com/uYXQnj7.png

Pokemon Display (iPhone 6/7/8)
https://i.imgur.com/V9tB1kc.png

Pokemon Edit (Desktop)
https://i.imgur.com/Vz78q71.png

Pokemon Edit (iPhone 6/7/8)
https://i.imgur.com/6waUUDu.png

**Pull request merged**
